### ISSUE TITLE
telepathy-gabble-plus RPM

### ISSUE THREAD

**Issue by ghost** [noonien-d/telepathy-gabble-old#3]
Two things:

- The telepathy-gabble-plus RPM available on your website doesn't have the chat marker functionality, I suppose it wasn't updated to reflect the latest changes in the source code.
- Is it possible to provide an RPM for i486 architectures?

Thanks!

**Comment by noonien-d** [comment]
- I uploaded a more recent version. Also, notice the new _force_ options, as _jolla-messages_ won't request receipts by default. Force will also overwrite receivers capabilities.
- untested i486 rpm added

**Comment by ghost** [comment]
Thanks!

**Comment by noonien-d** [comment]
You're welcome!
