### ISSUE TITLE
Provide upstream with MR

### ISSUE THREAD

**Issue by cnlpete** [noonien-d/telepathy-gabble-old#4]
There seems to be some activity over at Telepathy, given the recent mailinglist activity.

maybe you could provide Merge Requests against https://github.com/TelepathyIM/telepathy-gabble so yor extensions could actually land in upstream?

**Comment by detrout** [comment]
Yes come visit us! telepathy@lists.freedesktop.org I'm beginning to have small amounts of time again.

**Comment by schmittlauch** [comment]
*bump*

**Comment by noonien-d** [comment]
Pull requests are files in the upstream project https://github.com/TelepathyIM/telepathy-gabble/pulls

(this github repo is dead as I forked a new one for the PR feature)
